# Starter pipeline


# Starter pipeline    
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

# TODO: Replace the agent pool name
pool: newpool

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'devopsserviceconnection'

  # Web app name
  webAppName: 'flaskcicdproject4'

  # Agent VM image name
  vmImageName: 'myLinuxVM'

  # Environment name
  environmentName: 'flask-ml-service'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.7
  pythonVersion: '3.7'

